name: feathersjs_demo_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  dio: ^5.1.1
  flutter:
    sdk: flutter
  flutter_feathersjs: ^4.1.3
  flutter_slidable: ^3.0.0
  logger: ^1.3.0
  socket_io_client: ^1.0.2
  username_gen: ^1.0.4

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  fonts:
    - family: Abel
      fonts:
        - asset: assets/fonts/Abel-Regular.ttf
